name: word_template
description: Create a docx from a word template
version: 0.0.1

homepage: https://github.com/AlexandreMaillot/word_template

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.3.0
  xml: ^6.1.0
  collection: ^1.16.0
  path: ^1.8.2
  pdf: ^3.8.1
dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.3
  flutter_lints: ^2.0.1